title: "Kishore Kumar Behera - Senior DevOps/SRE/Platform Engineer"
description: "Portfolio of Kishore Kumar Behera, showcasing skills, projects, and experience as a Senior Platform Engineer."
baseurl: "" # Replace with your repository name if it's a project site
url: "https://unplugged-kk.github.io"

# Theme
theme: jekyll-theme-minimal # Replace with your chosen theme

# Markdown
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Other settings
highlighter: rouge
