name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # Update to the latest stable Ruby version
        bundler-cache: false # Disable bundler-cache

    - name: Update RubyGems and install latest Bundler
      run: |
        gem update --system
        gem install bundler
        bundle --version

    - name: Install dependencies
      run: bundle install

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        publish_dir: ./_site