name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false

    - name: Update RubyGems and install specific Bundler version
      run: |
        gem update --system 3.4.22
        gem install bundler -v 2.4.22
        gem uninstall bundler -v '!= 2.4.22'

    - name: Install dependencies
      run: |
        /opt/hostedtoolcache/Ruby/3.2.5/x64/bin/bundle _2.4.22_ config set --local path 'vendor/bundle'
        /opt/hostedtoolcache/Ruby/3.2.5/x64/bin/bundle _2.4.22_ install

    - name: Build site
      run: /opt/hostedtoolcache/Ruby/3.2.5/x64/bin/bundle _2.4.22_ exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site